server:
  port: 48093

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:59092}
    topic:
      orchestrator: orchestrator
      update-success: update-success
      update-fail: update-fail
    consumer:
      group-id: update-group
      auto-offset-reset: latest

  data:
    mongodb:
      uri: mongodb://${USER_NAME:update}:${USER_PASS:update}@mongodb:${DB_PORT:57013}/${DB_NAME:update-db}

logging:
  level:
    org:
      apache:
        kafka: OFF
