version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhaGigante2@
      MYSQL_DATABASE: vivo
      MYSQL_USER: wizardry
      MYSQL_PASSWORD: maosMacias2@
    ports:
      - "53306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  orchestrator-saga:
    driver: bridge