version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: update-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: update
      MONGO_INITDB_ROOT_PASSWORD: update
      MONGO_INITDB_DATABASE: update-db
    ports:
      - "57013:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
