version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-description-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: description
      MONGO_INITDB_ROOT_PASSWORD: description
      MONGO_INITDB_DATABASE: description-db
    ports:
      - "27010:27017"
    volumes:
      - mongo_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  mongo_data:
  kafka_data: