version: '3.8'

networks:
  orchestrator-saga:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: order-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: order
      MONGO_INITDB_ROOT_PASSWORD: order
      MONGO_INITDB_DATABASE: order-db
    ports:
      - "57010:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: