server:
  port: 8070

  datasource:
    url: jdbc:postgresql://${DB_HOST:vivo-db}:${DB_PORT:5432}/${DB_NAME:vivo-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      apache:
        kafka: OFF