server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      description-success: description-success
      description-fail: description-fail
    consumer:
      group-id: product-group
      auto-offset-reset: latest

  data:
    mongodb:
      uri: mongodb://description:description@mongodb:27010/description-db

logging:
  level:
    org:
      apache:
        kafka: OFF
