server:
  port: 48092

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:59092}
    topic:
      orchestrator: orchestrator
      search-success: search-success
      search-fail: search-fail
    consumer:
      group-id: search-group
      auto-offset-reset: latest

  data:
    mongodb:
      uri: mongodb://${USER_NAME:search}:${USER_PASS:search}@mongodb:${DB_PORT:57012}/${DB_NAME:search-db}

logging:
  level:
    org:
      apache:
        kafka: OFF
