spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/vivo
    username: wizardry
    password: maosMacias2@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
