server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:59092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest

  data:
    mongodb:
      uri: mongodb://${USER_NAME:order}:${USER_PASS:order}@mongodb:${DB_PORT:57010}/${DB_NAME:order-db}

logging:
  level:
    org:
      apache:
        kafka: OFF
