version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: item-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: item
      MONGO_INITDB_ROOT_PASSWORD: item
      MONGO_INITDB_DATABASE: item-db
    ports:
      - "57011:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
