server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest

   data:
    mongodb:
      uri: mongodb://product:product@mongodb:27012/product-db

logging:
  level:
    org:
      apache:
        kafka: OFF
