server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:59092}
    topic:
      orchestrator: orchestrator
      description-success: search-success
      description-fail: search-fail
    consumer:
      group-id: product-group
      auto-offset-reset: latest

  data:
    mongodb:
      uri: mongodb://${USER_NAME:item}:${USER_PASS:item}@mongodb:${DB_PORT:57011}/${DB_NAME:item-db}

logging:
  level:
    org:
      apache:
        kafka: OFF
